version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - goodjob-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=au2
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - goodjob-network

networks:
  goodjob-network:
    driver: bridge

volumes:
  mysql-data: 